/* Aloud — curated global university list for the registration affiliation
 * picker. Searchable substring match; users can also type a custom value if
 * theirs isn't listed. Format: "Name, Country". (~220 institutions, with
 * strong Hungarian + global coverage.) */
window.PR_UNIVERSITIES = [
  // ---- Hungary ---- (English name + Hungarian name so either can be typed to find it)
  "Eötvös Loránd University (ELTE) – Eötvös Loránd Tudományegyetem, Hungary",
  "Budapest University of Technology and Economics (BME) – Budapesti Műszaki és Gazdaságtudományi Egyetem, Hungary",
  "University of Szeged (SZTE) – Szegedi Tudományegyetem, Hungary",
  "University of Debrecen (DE) – Debreceni Egyetem, Hungary",
  "University of Pécs (PTE) – Pécsi Tudományegyetem, Hungary",
  "Semmelweis University – Semmelweis Egyetem, Hungary",
  "Corvinus University of Budapest – Budapesti Corvinus Egyetem, Hungary",
  "Óbuda University – Óbudai Egyetem, Hungary",
  "University of Pannonia – Pannon Egyetem, Hungary",
  "University of Miskolc – Miskolci Egyetem, Hungary",
  "Széchenyi István University (SZE) – Széchenyi István Egyetem, Hungary",
  "Hungarian University of Agriculture and Life Sciences (MATE) – Magyar Agrár- és Élettudományi Egyetem, Hungary",
  "University of Sopron – Soproni Egyetem, Hungary",
  "Pázmány Péter Catholic University (PPKE) – Pázmány Péter Katolikus Egyetem, Hungary",
  "Central European University (CEU) – Közép-európai Egyetem, Hungary",
  "Moholy-Nagy University of Art and Design (MOME) – Moholy-Nagy Művészeti Egyetem, Hungary",
  "Liszt Ferenc Academy of Music – Liszt Ferenc Zeneművészeti Egyetem, Hungary",
  "John von Neumann University (NJE) – Neumann János Egyetem, Kecskemét, Hungary",
  "Eszterházy Károly Catholic University – Eszterházy Károly Katolikus Egyetem, Hungary",
  "University of Nyíregyháza – Nyíregyházi Egyetem, Hungary",
  "University of Dunaújváros – Dunaújvárosi Egyetem, Hungary",
  "Andrássy University Budapest – Andrássy Gyula Budapesti Német Nyelvű Egyetem, Hungary",
  "University of Veterinary Medicine Budapest (ÁTE) – Állatorvostudományi Egyetem, Hungary",
  "Budapest Metropolitan University (METU) – Budapesti Metropolitan Egyetem, Hungary",
  "Milton Friedman University – Milton Friedman Egyetem, Hungary",
  "National University of Public Service (NKE) – Nemzeti Közszolgálati Egyetem, Hungary",
  "HUN-REN (Hungarian Research Network) – Magyar Kutatási Hálózat, Hungary",
  // ---- United States ----
  "Massachusetts Institute of Technology (MIT), USA",
  "Stanford University, USA",
  "Harvard University, USA",
  "California Institute of Technology (Caltech), USA",
  "Princeton University, USA",
  "University of California, Berkeley, USA",
  "University of California, Los Angeles (UCLA), USA",
  "University of Chicago, USA",
  "Yale University, USA",
  "Columbia University, USA",
  "Cornell University, USA",
  "University of Pennsylvania, USA",
  "Johns Hopkins University, USA",
  "University of Michigan, USA",
  "Carnegie Mellon University, USA",
  "Duke University, USA",
  "Northwestern University, USA",
  "New York University (NYU), USA",
  "University of Washington, USA",
  "Georgia Institute of Technology, USA",
  "University of Texas at Austin, USA",
  "University of Illinois Urbana-Champaign, USA",
  "University of Wisconsin-Madison, USA",
  "University of California, San Diego, USA",
  "Brown University, USA",
  "Boston University, USA",
  "Purdue University, USA",
  "Pennsylvania State University, USA",
  "University of Maryland, College Park, USA",
  "University of Minnesota, USA",
  "Ohio State University, USA",
  "University of North Carolina at Chapel Hill, USA",
  "Rice University, USA",
  "Vanderbilt University, USA",
  "Washington University in St. Louis, USA",
  // ---- United Kingdom ----
  "University of Oxford, United Kingdom",
  "University of Cambridge, United Kingdom",
  "Imperial College London, United Kingdom",
  "University College London (UCL), United Kingdom",
  "London School of Economics (LSE), United Kingdom",
  "University of Edinburgh, United Kingdom",
  "King's College London, United Kingdom",
  "University of Manchester, United Kingdom",
  "University of Bristol, United Kingdom",
  "University of Warwick, United Kingdom",
  "University of Glasgow, United Kingdom",
  "University of Birmingham, United Kingdom",
  "University of Leeds, United Kingdom",
  "University of Sheffield, United Kingdom",
  "University of Nottingham, United Kingdom",
  "University of Southampton, United Kingdom",
  "Durham University, United Kingdom",
  "Queen Mary University of London, United Kingdom",
  // ---- Germany ----
  "Technical University of Munich (TUM), Germany",
  "Ludwig Maximilian University of Munich (LMU), Germany",
  "Heidelberg University, Germany",
  "Humboldt University of Berlin, Germany",
  "Free University of Berlin, Germany",
  "RWTH Aachen University, Germany",
  "Karlsruhe Institute of Technology (KIT), Germany",
  "University of Freiburg, Germany",
  "University of Bonn, Germany",
  "University of Göttingen, Germany",
  "University of Hamburg, Germany",
  "Technical University of Berlin, Germany",
  "University of Tübingen, Germany",
  "University of Stuttgart, Germany",
  // ---- France ----
  "Paris Sciences et Lettres (PSL), France",
  "Institut Polytechnique de Paris, France",
  "Sorbonne University, France",
  "Université Paris-Saclay, France",
  "École Polytechnique, France",
  "Sciences Po, France",
  "ENS de Lyon, France",
  "Université Grenoble Alpes, France",
  "Aix-Marseille University, France",
  // ---- Rest of Europe ----
  "ETH Zürich, Switzerland",
  "EPFL (École Polytechnique Fédérale de Lausanne), Switzerland",
  "University of Zürich, Switzerland",
  "University of Geneva, Switzerland",
  "Delft University of Technology, Netherlands",
  "University of Amsterdam, Netherlands",
  "Utrecht University, Netherlands",
  "Leiden University, Netherlands",
  "Eindhoven University of Technology, Netherlands",
  "Wageningen University & Research, Netherlands",
  "KU Leuven, Belgium",
  "Ghent University, Belgium",
  "Université catholique de Louvain, Belgium",
  "Karolinska Institute, Sweden",
  "KTH Royal Institute of Technology, Sweden",
  "Lund University, Sweden",
  "Uppsala University, Sweden",
  "Stockholm University, Sweden",
  "University of Copenhagen, Denmark",
  "Technical University of Denmark (DTU), Denmark",
  "Aarhus University, Denmark",
  "University of Oslo, Norway",
  "Norwegian University of Science and Technology (NTNU), Norway",
  "University of Helsinki, Finland",
  "Aalto University, Finland",
  "University of Vienna, Austria",
  "Vienna University of Technology (TU Wien), Austria",
  "University of Innsbruck, Austria",
  "ETH Lausanne, Switzerland",
  "Politecnico di Milano, Italy",
  "Sapienza University of Rome, Italy",
  "University of Bologna, Italy",
  "University of Padua, Italy",
  "Scuola Normale Superiore di Pisa, Italy",
  "University of Milan, Italy",
  "Universitat de Barcelona, Spain",
  "Autonomous University of Madrid, Spain",
  "Complutense University of Madrid, Spain",
  "Universitat Politècnica de Catalunya, Spain",
  "Pompeu Fabra University, Spain",
  "University of Lisbon, Portugal",
  "University of Porto, Portugal",
  "Charles University, Czech Republic",
  "Czech Technical University in Prague, Czech Republic",
  "Masaryk University, Czech Republic",
  "Jagiellonian University, Poland",
  "University of Warsaw, Poland",
  "Warsaw University of Technology, Poland",
  "AGH University of Krakow, Poland",
  "Comenius University Bratislava, Slovakia",
  "Slovak University of Technology, Slovakia",
  "University of Ljubljana, Slovenia",
  "University of Zagreb, Croatia",
  "University of Belgrade, Serbia",
  "University of Bucharest, Romania",
  "Babeș-Bolyai University, Romania",
  "Politehnica University of Bucharest, Romania",
  "Sofia University, Bulgaria",
  "University of Vienna, Austria",
  "National and Kapodistrian University of Athens, Greece",
  "Aristotle University of Thessaloniki, Greece",
  "University of Tartu, Estonia",
  "Vilnius University, Lithuania",
  "University of Latvia, Latvia",
  // ---- Asia ----
  "Tsinghua University, China",
  "Peking University, China",
  "Fudan University, China",
  "Shanghai Jiao Tong University, China",
  "Zhejiang University, China",
  "University of Science and Technology of China, China",
  "Nanjing University, China",
  "University of Hong Kong, Hong Kong",
  "Hong Kong University of Science and Technology, Hong Kong",
  "Chinese University of Hong Kong, Hong Kong",
  "National University of Singapore (NUS), Singapore",
  "Nanyang Technological University (NTU), Singapore",
  "University of Tokyo, Japan",
  "Kyoto University, Japan",
  "Osaka University, Japan",
  "Tokyo Institute of Technology, Japan",
  "Tohoku University, Japan",
  "Seoul National University, South Korea",
  "KAIST, South Korea",
  "POSTECH, South Korea",
  "Yonsei University, South Korea",
  "Korea University, South Korea",
  "Indian Institute of Science (IISc), India",
  "Indian Institute of Technology Bombay, India",
  "Indian Institute of Technology Delhi, India",
  "Indian Institute of Technology Madras, India",
  "Indian Institute of Technology Kanpur, India",
  "National Taiwan University, Taiwan",
  "Tel Aviv University, Israel",
  "Hebrew University of Jerusalem, Israel",
  "Technion - Israel Institute of Technology, Israel",
  "Weizmann Institute of Science, Israel",
  "King Abdullah University of Science and Technology (KAUST), Saudi Arabia",
  // ---- Oceania ----
  "University of Melbourne, Australia",
  "University of Sydney, Australia",
  "Australian National University, Australia",
  "University of Queensland, Australia",
  "Monash University, Australia",
  "University of New South Wales (UNSW), Australia",
  "University of Auckland, New Zealand",
  // ---- Canada ----
  "University of Toronto, Canada",
  "University of British Columbia, Canada",
  "McGill University, Canada",
  "University of Waterloo, Canada",
  "University of Montreal, Canada",
  "McMaster University, Canada",
  "University of Alberta, Canada",
  // ---- Latin America & Africa ----
  "University of São Paulo, Brazil",
  "University of Campinas (Unicamp), Brazil",
  "National Autonomous University of Mexico (UNAM), Mexico",
  "University of Buenos Aires, Argentina",
  "University of Chile, Chile",
  "Pontifical Catholic University of Chile, Chile",
  "University of Cape Town, South Africa",
  "University of the Witwatersrand, South Africa",
  "Cairo University, Egypt"
];
